### ISSUE TITLE
add section about command line arguments

### ISSUE THREAD

**Issue by mipmip** [GeopJr/ultimate-gtk4-crystal-guide#5]
Difficult to get the official GTK way of handling cli operations working. E.g.

- defining flags and key/value arguments
- reading given arguments
- command line signal
- open signal

**Comment by GeopJr** [comment]
I added open signal and CLI flags but it might not be exactly what you are looking for.

CLI args are being handled by Crystal's OptionParser instead of using Option{Context, Entry, Group}. This is because gi-crystal (the binding generator) is purposely ignoring them:

> The rule is simple: If it's possible to write the same code in Crystal stdlib, ignore the GLib function.
>
> https://github.com/hugopl/gi-crystal/commit/802dc0cff4559ee5513bf158d21cf1bd254de208

If you have a legit need for them, please open an issue on gi-crystal: https://github.com/hugopl/gi-crystal/issues/new

Otherwise, the page should be up: https://ultimate-gtk4-crystal-guide.geopjr.dev/en/extra/cli.html

> **Note**
> open_signal works as expected, the above comments are on CLI flags only
